//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStoreApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GorceryStoreEntities : DbContext
    {
        public GorceryStoreEntities()
            : base("name=GorceryStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_INFO> TB_INFO { get; set; }
        public virtual DbSet<TB_Procurement> TB_Procurement { get; set; }
        public virtual DbSet<TB_Suppliers> TB_Suppliers { get; set; }
        public virtual DbSet<TB_User> TB_User { get; set; }
        public virtual DbSet<TB_Customer2> TB_Customer2 { get; set; }
        public virtual DbSet<TB_Productt> TB_Productt { get; set; }
        public virtual DbSet<TB_Saless> TB_Saless { get; set; }
    }
}
