//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStoreApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Saless
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int SellerID { get; set; }
        public int BuyerID { get; set; }
        public string TheTotalAmount { get; set; }
        public string DATE { get; set; }
    
        public virtual TB_Customer2 TB_Customer2 { get; set; }
        public virtual TB_Productt TB_Productt { get; set; }
        public virtual TB_User TB_User { get; set; }
    }
}
