using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace GroceryStoreApp.pl
{
    public partial class Product_FORM : Form
    {
        GorceryStoreEntities DB = new GorceryStoreEntities();
        TB_Productt TB_Productt1 = new TB_Productt();
        public int id;
        public Product_FORM()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            GroceryStoreApp.GorceryStoreEntities dbContext = new GroceryStoreApp.GorceryStoreEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_Productt.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControl1.DataSource = dbContext.TB_Productt.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        //display Product_Add_Form
        private void Add_Click(object sender, EventArgs e)
        {
            pl.Product_Add product_Add = new Product_Add();
            product_Add.Show();
        }
        //refresh
        private void Refresh_Click(object sender, EventArgs e)
        {
            update1();
        }

        private void update1()
        {
            DB = new GorceryStoreEntities();
            gridControl1.DataSource = DB.TB_Productt.ToList();
        }

        //Edit 
        private void Edit_Click(object sender, EventArgs e)
        {

            pl.Product_Add product_Add = new Product_Add();
            id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
            TB_Productt1 = DB.TB_Productt.Where(x => x.ID == id).FirstOrDefault();
            product_Add.textName.Text = TB_Productt1.Name.ToString();
            product_Add.textprice.Text = TB_Productt1.Price.ToString();
            product_Add.textProductionDate.Text = TB_Productt1.ProductionsDate.ToString();
            product_Add.textExpirationDate.Text = TB_Productt1.ExpirationDate.ToString();
            product_Add.id = id;
            product_Add.Show();
        }
        //Delete
        private void Delete_Click(object sender, EventArgs e)
        {
            id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
            TB_Productt1 = DB.TB_Productt.Where(x => x.ID == id).FirstOrDefault();
            DB.Entry(TB_Productt1).State = EntityState.Deleted;
            DB.SaveChanges();
            update1();
            MessageBox.Show("one row has been deleted");
        }
        //Searching by Name
        private void btn_search_Click(object sender, EventArgs e)
        {
            var serch = text_search.Text;
            gridControl1.DataSource = DB.TB_Productt.Where(x => x.Name.Contains(serch)).ToList();
        }
    }
}
