using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace GroceryStoreApp.pl
{
    public partial class Supplier_FORM : Form
    {
        GorceryStoreEntities DB = new GorceryStoreEntities();
        TB_Suppliers TB_Suppliers1 = new TB_Suppliers();
        public int id;
        public Supplier_FORM()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            GroceryStoreApp.GorceryStoreEntities dbContext = new GroceryStoreApp.GorceryStoreEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_Suppliers.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControl1.DataSource = dbContext.TB_Suppliers.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        // to show add form
        private void Add_Click(object sender, EventArgs e)
        {
            pl.Supplier_Add Supplier_Add = new Supplier_Add();
            Supplier_Add.Show();
        }
        //Refresh
        private void Refresh_Click(object sender, EventArgs e)
        {
            Uppdat_data();
        }
        private void Uppdat_data()
        {
            DB = new GorceryStoreEntities();
            gridControl1.DataSource = DB.TB_Suppliers.ToList();
        }

        // Delete data
        private void Delete_Click(object sender, EventArgs e)
        {
            id =Convert.ToInt32( gridView1.GetFocusedRowCellValue("ID"));
            TB_Suppliers1 = DB.TB_Suppliers.Where(x => x.ID == id).FirstOrDefault();
            DB.Entry(TB_Suppliers1).State = EntityState.Deleted;
            DB.SaveChanges();
            Uppdat_data();
            MessageBox.Show("one row has been deleted");
        }
        //Edit Data
        private void Edit_Click(object sender, EventArgs e)
        {
            pl.Supplier_Add supplier_Add = new Supplier_Add();
            id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
            TB_Suppliers1 = DB.TB_Suppliers.Where(x => x.ID == id).FirstOrDefault();
            supplier_Add.textFirstName.Text = TB_Suppliers1.FirstName.ToString();
            supplier_Add.textLastName.Text = TB_Suppliers1.LastName.ToString();
            supplier_Add.textPhone.Text = TB_Suppliers1.Phone.ToString();
            supplier_Add.textEmail.Text = TB_Suppliers1.Email.ToString();
            supplier_Add.textAddress.Text = TB_Suppliers1.Address.ToString();
            supplier_Add.id = id;
            supplier_Add.Show();

        }

        private void btn_search_Click(object sender, EventArgs e)
        {
            var search = text_search.Text;
            gridControl1.DataSource = DB.TB_Suppliers.Where(x => x.FirstName.Contains(search)).ToList();
        }
    }
}
